import Head from 'next/head';
import Upload from '../components/FileInput';

export default function Home() {
  return (
    <div className={``}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Upload />
    </div>
  );
}
